refresh-sdk:
  stage: build
  image: php
  before_script:
    - apt-get update
    - apt-get install -y wget make zip git
    - git config --global user.email "ci@runner.git"
    - git config --global user.name "CI runner"
  script:
    - make generate
    - git add GD_SDK.7z
    - git commit -m "refresh SDK"
    - git push origin master https://${USERNAME}:${PASSWORD}@gitlab.com/IceExplosive/gdscript.git
