refresh-sdk:
  stage: build
  image: php
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "schedule"
#      when: always
  before_script:
    - apt-get update
    - apt-get install -y wget make zip git
    - git config --global user.email "ci@runner.git"
    - git config --global user.name "CI runner"
  script:
    - cd php
    - UPDATED=$(php sdkBuilder.php)
    - cd ..
    - |
      if [[ $UPDATED == 0 ]]; then
        git add .
        git commit -m "refresh SDK"
        git push https://${USERNAME}:${PASSWORD}@gitlab.com/IceExplosive/gdscript.git HEAD:master
      fi
