refresh-sdk:
  stage: build
  image: php
  before_script:
    - apt-get update
    - apt-get install -y wget make zip git
  script:
    - make generate
    - git init
    - git remote set-url origin https://gitlab.com/IceExplosive/gdscript.git
    - git add GD_SDK.7z
    - git commit -m "refresh SDK"
    - git push https://${USERNAME}:${PASSWORD}@gitlab.com/IceExplosive/gdscript.git
